ruby '3.2.2'

source 'https://rubygems.org'

gem 'rack', '~> 3'
gem 'rack-contrib', '~> 2.4.0'
gem 'sinatra', '~> 4'
gem 'sinatra-contrib', '~> 4'
gem "haml", "~> 6"
gem 'padrino-helpers', "~> 0.15"
gem 'dynamoid', git: 'https://github.com/Dynamoid/dynamoid.git', branch: 'master' # waiting for a release > v3.10.0 on 2/10/2024
gem "rexml", "~> 3.2.6"
# gem "aws-sdk-s3", "~> 1.131" # s3
# gem "aws-sdk-ses", "~> 1.55.0" # email

group :development do
  gem "rackup", "~> 2.1"
  gem 'puma', '~> 6'
  gem 'dotenv', '~> 3'
  gem 'rerun', '~> 0.14'
end
